### ISSUE TITLE
Error in ResponsivePaddingCollection.xs

### ISSUE THREAD

**Issue by timbell** [AlexanderThiele/responsive_spacing#1]
I believe there's a copy/paste error [here](https://github.com/AlexanderThiele/responsive_spacing/blob/b6ed8b9f1ddc94b8053952c1fd7325d58de92650/lib/models/responsive_collection.dart#L111) in `ResponsivePaddingCollection` - should be `ScaledSize xs(double width) => const ScaledPadding.xs()` ?

**Comment by AlexanderThiele** [comment]
@timbell Great catch!

Do you want to open a PR or should i fix it?

**Comment by timbell** [comment]
Happy to do a PR...
